//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vergosity.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vergosity.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuildMotion.lic.
        /// </summary>
        internal static string BuildMotionLicense {
            get {
                return ResourceManager.GetString("BuildMotionLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The license for the Vergosity framework cannot be found. Make sure a valid license is configured in the buildmotion.lic file. This file should be located in the output directory of the application..
        /// </summary>
        internal static string BuildMotionLicenseNotFound {
            get {
                return ResourceManager.GetString("BuildMotionLicenseNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Build Motion license has expired..
        /// </summary>
        internal static string ExpiredBuildMotionLicense {
            get {
                return ResourceManager.GetString("ExpiredBuildMotionLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The component configuration for the license is not valid. Cannot validate license with missing or invalid information. Please confirm that the license is configured..
        /// </summary>
        internal static string InvalidComponentConfigurationMessage {
            get {
                return ResourceManager.GetString("InvalidComponentConfigurationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} license information is not valid for the licensee {1} at {2}..
        /// </summary>
        internal static string InvalidComponentLicenseMessage {
            get {
                return ResourceManager.GetString("InvalidComponentLicenseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The license configuration for the license is not valid. Cannot validate license with missing or invalid information. Please confirm that the license is configured. If the license information was modified, the license may be in an invalid state - do not modify the information in the license file..
        /// </summary>
        internal static string InvalidLicenseConfigurationMessage {
            get {
                return ResourceManager.GetString("InvalidLicenseConfigurationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error retrieving the specified license information. .
        /// </summary>
        internal static string LicenseConfigurationMessage {
            get {
                return ResourceManager.GetString("LicenseConfigurationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The license [{0}] has expired on [{1}]. The application has exceeded the use of the license Expiration Date in the BuildMotion.lic file. Please renew your BuildMotion license or update the .lic file with updated license information..
        /// </summary>
        internal static string LicenseExpired {
            get {
                return ResourceManager.GetString("LicenseExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuildMotion.lic.
        /// </summary>
        internal static string licenseName {
            get {
                return ResourceManager.GetString("licenseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vergosity.Configuration.
        /// </summary>
        internal static string LicenseSectionGroupName {
            get {
                return ResourceManager.GetString("LicenseSectionGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find or load the LicenseSectionGroupName [BuildMotion.Configuration]. .
        /// </summary>
        internal static string LicenseSectionGroupNotFound {
            get {
                return ResourceManager.GetString("LicenseSectionGroupNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;RSAKeyValue&gt;&lt;Modulus&gt;1+qaaVNx5O72U6jj+KGjrX3ENGDyq0bXsAOuHdEWtS2sheBkUdTHzgY+VX1CXrLajZ5p8XtcIn8As4Qky++l2sRJIfXAzljU6M7Oam/Im1T4dNH9XAGc2nztBsvIDXmuTJ9oyow4/ySTsOjA8he5vG07yB4tCgk8RE/8+D54KK6/cxJPfDJ1H84YiPGuoo3Lc5RU/AwsqWcTEqrBTuCOE8ysdzZueFcNFYRSnrZ9G4BUJbr80SoAH6C3ULTiH//zVSls9B4iZez6aVFQDX7BUgMdD/vqD0Q/NAJXPytCRIqm6/RPPp48sX/TzrsTtJLCZFvibHektjL5aQNwaW8mb2WJbEvfGZCCP9JbK+XZDXhIUQ+wF15d5IFrAwD/XB8xfsX1jD6jZ25ZfVPnid6km6tnCNSwIeFxIzbrxkr1SSsKqQ8JB1E8MhC0yTjo4FaeDlIRyYChPdbEPbh4vgP6qa558iIQ96sEW12h5CRAXR [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PublicKey {
            get {
                return ResourceManager.GetString("PublicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected business action exception..
        /// </summary>
        internal static string UnexpectedActionException {
            get {
                return ResourceManager.GetString("UnexpectedActionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected license exception..
        /// </summary>
        internal static string UnexpectedLicenseException {
            get {
                return ResourceManager.GetString("UnexpectedLicenseException", resourceCulture);
            }
        }
    }
}
